apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  orderdb_url: mongodb+srv://admin:Admin%40123@order-cluster.hefja7b.mongodb.net/?retryWrites=true&w=majority&appName=order-cluster
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka
  userdb_url: jdbc:mysql://mydb.cv2qcia2mc4z.ap-south-1.rds.amazonaws.com:3306/userdb
  restaurantdb_url: jdbc:mysql://mydb.cv2qcia2mc4z.ap-south-1.rds.amazonaws.com:3306/restaurantdb
  foodcataloguedb_url: jdbc:mysql://mydb.cv2qcia2mc4z.ap-south-1.rds.amazonaws.com:3306/foodcataloguedb
  

  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
  